INSERT INTO movies (title, year, description, rating) VALUES
('Echoes of Tomorrow', 2008, 'A thrilling story about echoes of tomorrow and the choices that define our fate.', 5.2),
('Shadow of the Past', 2024, 'A thrilling story about shadow of the past and the choices that define our fate.', 9.8),
('Whispers in the Wind', 2004, 'A thrilling story about whispers in the wind and the choices that define our fate.', 8.4),
('Chasing the Horizon', 2012, 'A thrilling story about chasing the horizon and the choices that define our fate.', 9.7),
('Forgotten Legends', 1993, 'A thrilling story about forgotten legends and the choices that define our fate.', 7.5),
('Fading Echoes', 2011, 'A thrilling story about fading echoes and the choices that define our fate.', 6.0),
('Silent Promises', 2014, 'A thrilling story about silent promises and the choices that define our fate.', 8.9),
('Crimson Night', 2008, 'A thrilling story about crimson night and the choices that define our fate.', 9.3),
('Dawn Breakers', 1999, 'A thrilling story about dawn breakers and the choices that define our fate.', 7.9),
('Shattered Realities', 2019, 'A thrilling story about shattered realities and the choices that define our fate.', 6.7),
('Beyond the Mist', 2001, 'A thrilling story about beyond the mist and the choices that define our fate.', 7.3),
('Endless Skies', 2005, 'A thrilling story about endless skies and the choices that define our fate.', 8.1),
('Twilight Memories', 2016, 'A thrilling story about twilight memories and the choices that define our fate.', 9.1),
('Parallel Lines', 2013, 'A thrilling story about parallel lines and the choices that define our fate.', 6.8),
('Golden Horizon', 2006, 'A thrilling story about golden horizon and the choices that define our fate.', 8.5),
('Burning Silence', 2007, 'A thrilling story about burning silence and the choices that define our fate.', 6.2),
('Last Refuge', 1998, 'A thrilling story about last refuge and the choices that define our fate.', 7.4),
('Eyes of the Storm', 2003, 'A thrilling story about eyes of the storm and the choices that define our fate.', 7.7),
('Winds of Destiny', 2010, 'A thrilling story about winds of destiny and the choices that define our fate.', 8.6),
('Frozen Tears', 2000, 'A thrilling story about frozen tears and the choices that define our fate.', 6.9),
('The Silent Path', 2015, 'A thrilling story about the silent path and the choices that define our fate.', 9.4),
('Broken Compass', 2009, 'A thrilling story about broken compass and the choices that define our fate.', 7.2),
('Celestial Bonds', 2022, 'A thrilling story about celestial bonds and the choices that define our fate.', 8.8),
('Veil of Time', 2002, 'A thrilling story about veil of time and the choices that define our fate.', 7.0),
('Nightfall Rising', 2018, 'A thrilling story about nightfall rising and the choices that define our fate.', 8.3);
INSERT INTO movies (title, year, description, rating) VALUES
('Tides of Fate', 2007, 'A thrilling story about tides of fate and the choices that define our fate.', 6.6),
('Beneath the Ashes', 2003, 'A thrilling story about beneath the ashes and the choices that define our fate.', 7.1),
('Mirage Streets', 2006, 'A thrilling story about mirage streets and the choices that define our fate.', 7.8),
('Fragments of Light', 2011, 'A thrilling story about fragments of light and the choices that define our fate.', 9.0),
('Radiant Dusk', 2017, 'A thrilling story about radiant dusk and the choices that define our fate.', 8.0),
('Hollow Truths', 2012, 'A thrilling story about hollow truths and the choices that define our fate.', 6.3),
('Echo Chamber', 2020, 'A thrilling story about echo chamber and the choices that define our fate.', 8.7),
('Ashen Skies', 2004, 'A thrilling story about ashen skies and the choices that define our fate.', 7.6),
('Flicker of Hope', 2015, 'A thrilling story about flicker of hope and the choices that define our fate.', 8.2),
('Cradle of Storms', 1995, 'A thrilling story about cradle of storms and the choices that define our fate.', 6.5),
('Phantom Veins', 1996, 'A thrilling story about phantom veins and the choices that define our fate.', 7.9),
('The Dimming Light', 1994, 'A thrilling story about the dimming light and the choices that define our fate.', 6.7),
('Whirlwind', 1997, 'A thrilling story about whirlwind and the choices that define our fate.', 7.3),
('Serenity Lost', 1993, 'A thrilling story about serenity lost and the choices that define our fate.', 6.8),
('Edge of Shadows', 2016, 'A thrilling story about edge of shadows and the choices that define our fate.', 8.5),
('The Glass Thread', 1998, 'A thrilling story about the glass thread and the choices that define our fate.', 6.1),
('Vortex Dreams', 2010, 'A thrilling story about vortex dreams and the choices that define our fate.', 7.0),
('The Gilded Cage', 2002, 'A thrilling story about the gilded cage and the choices that define our fate.', 7.4),
('Still Waters', 1999, 'A thrilling story about still waters and the choices that define our fate.', 6.4),
('The Last Ember', 2001, 'A thrilling story about the last ember and the choices that define our fate.', 7.2),
('Maze of Reflections', 2013, 'A thrilling story about maze of reflections and the choices that define our fate.', 8.6),
('Bleeding Horizon', 2005, 'A thrilling story about bleeding horizon and the choices that define our fate.', 6.9),
('Veins of Steel', 2008, 'A thrilling story about veins of steel and the choices that define our fate.', 7.5),
('Tempest Shore', 2000, 'A thrilling story about tempest shore and the choices that define our fate.', 6.7),
('The Endless Fall', 2019, 'A thrilling story about the endless fall and the choices that define our fate.', 9.2);
INSERT INTO movies (title, year, description, rating) VALUES
('Winter Hollow', 2011, 'A thrilling story about winter hollow and the choices that define our fate.', 7.1),
('Crimson Path', 2009, 'A thrilling story about crimson path and the choices that define our fate.', 6.8),
('Lanterns in the Mist', 2012, 'A thrilling story about lanterns in the mist and the choices that define our fate.', 8.4),
('Twilight Requiem', 2014, 'A thrilling story about twilight requiem and the choices that define our fate.', 7.7),
('Frozen Whispers', 2017, 'A thrilling story about frozen whispers and the choices that define our fate.', 7.5),
('The Silent Vault', 2006, 'A thrilling story about the silent vault and the choices that define our fate.', 6.2),
('The Whispering Flame', 2019, 'A thrilling story about the whispering flame and the choices that define our fate.', 9.0),
('The Pale Choir', 2008, 'A thrilling story about the pale choir and the choices that define our fate.', 7.3),
('Winds of Solace', 2013, 'A thrilling story about winds of solace and the choices that define our fate.', 8.0),
('Echoes of the Rift', 2015, 'A thrilling story about echoes of the rift and the choices that define our fate.', 8.5),
('The Crystal Wall', 2001, 'A thrilling story about the crystal wall and the choices that define our fate.', 6.4),
('Garden of Haze', 2016, 'A thrilling story about garden of haze and the choices that define our fate.', 7.9),
('Shattered Lantern', 2004, 'A thrilling story about shattered lantern and the choices that define our fate.', 6.7),
('The Hollow Throne', 2002, 'A thrilling story about the hollow throne and the choices that define our fate.', 7.2),
('Chains of Light', 2005, 'A thrilling story about chains of light and the choices that define our fate.', 6.9),
('Nebula’s Call', 2020, 'A thrilling story about nebula’s call and the choices that define our fate.', 9.1),
('Curtain of Embers', 2007, 'A thrilling story about curtain of embers and the choices that define our fate.', 6.5),
('The Forgotten Thread', 1999, 'A thrilling story about the forgotten thread and the choices that define our fate.', 6.3),
('Ivory Descent', 1995, 'A thrilling story about ivory descent and the choices that define our fate.', 7.6),
('Echo Drift', 2010, 'A thrilling story about echo drift and the choices that define our fate.', 7.4),
('The Shifting Tides', 2000, 'A thrilling story about the shifting tides and the choices that define our fate.', 6.6),
('Dust and Velvet', 2003, 'A thrilling story about dust and velvet and the choices that define our fate.', 7.0),
('The Cinder Bloom', 1997, 'A thrilling story about the cinder bloom and the choices that define our fate.', 6.9),
('Bridges of the Void', 1998, 'A thrilling story about bridges of the void and the choices that define our fate.', 6.8),
('The Sleeping Archive', 2006, 'A thrilling story about the sleeping archive and the choices that define our fate.', 7.3);
INSERT INTO movies (title, year, description, rating) VALUES
('Whispers of the Machine', 2018, 'A thrilling story about whispers of the machine and the choices that define our fate.', 8.3),
('The Violet Code', 2002, 'A thrilling story about the violet code and the choices that define our fate.', 7.0),
('Lucid Horizon', 2013, 'A thrilling story about lucid horizon and the choices that define our fate.', 7.5),
('Fables of Ash', 1999, 'A thrilling story about fables of ash and the choices that define our fate.', 6.7),
('Hollow Frequency', 2011, 'A thrilling story about hollow frequency and the choices that define our fate.', 7.4),
('Mirage Sonata', 2009, 'A thrilling story about mirage sonata and the choices that define our fate.', 7.1),
('The Eclipsed Shore', 2014, 'A thrilling story about the eclipsed shore and the choices that define our fate.', 7.8),
('Gilded Rain', 2007, 'A thrilling story about gilded rain and the choices that define our fate.', 6.8),
('The Iron Pact', 2006, 'A thrilling story about the iron pact and the choices that define our fate.', 7.2),
('Crows of Silence', 2001, 'A thrilling story about crows of silence and the choices that define our fate.', 6.6),
('Velvet Ember', 1998, 'A thrilling story about velvet ember and the choices that define our fate.', 7.0),
('Cradle of Haze', 2000, 'A thrilling story about cradle of haze and the choices that define our fate.', 6.9),
('The Burnt Psalm', 2003, 'A thrilling story about the burnt psalm and the choices that define our fate.', 6.7),
('Echoes in Crystal', 2005, 'A thrilling story about echoes in crystal and the choices that define our fate.', 7.3),
('Spectral Window', 2016, 'A thrilling story about spectral window and the choices that define our fate.', 8.0),
('The Last Broadcast', 2020, 'A thrilling story about the last broadcast and the choices that define our fate.', 8.7),
('Vortex Garden', 2019, 'A thrilling story about vortex garden and the choices that define our fate.', 7.9),
('The Fractured Mirror', 2004, 'A thrilling story about the fractured mirror and the choices that define our fate.', 7.2),
('Shadows of the Frame', 2015, 'A thrilling story about shadows of the frame and the choices that define our fate.', 8.1),
('Nocturne Abyss', 2017, 'A thrilling story about nocturne abyss and the choices that define our fate.', 7.6),
('The Infinite Veil', 2010, 'A thrilling story about the infinite veil and the choices that define our fate.', 7.4),
('Hymns of Dust', 2008, 'A thrilling story about hymns of dust and the choices that define our fate.', 6.5),
('Ashfall Memoir', 1996, 'A thrilling story about ashfall memoir and the choices that define our fate.', 6.9),
('Starlit Cage', 2001, 'A thrilling story about starlit cage and the choices that define our fate.', 7.0),
('The Obsidian Chapter', 2012, 'A thrilling story about the obsidian chapter and the choices that define our fate.', 7.8);
