INSERT INTO Actors (firstname, lastname, bio, rating) VALUES
('Robert', 'Downey Jr.', 'Known for his role as Iron Man in the Marvel Cinematic Universe.', 9.5),
('Scarlett', 'Johansson', 'Famous for her role as Black Widow.', 9.0),
('Chris', 'Evans', 'Played Captain America in the Marvel series.', 8.8),
('Chris', 'Hemsworth', 'Australian actor best known for Thor.', 8.7),
('Mark', 'Ruffalo', 'Played Bruce Banner/Hulk in the MCU.', 8.5),
('Jeremy', 'Renner', 'Played Hawkeye in the MCU.', 8.2),
('Tom', 'Holland', 'Young actor known as Spider-Man.', 8.9),
('Benedict', 'Cumberbatch', 'Doctor Strange and Sherlock Holmes.', 9.1),
('Chadwick', 'Boseman', 'Black Panther, known for impactful roles.', 9.6),
('Paul', 'Rudd', 'Comedic actor, known for Ant-Man.', 8.3),
('Chris', 'Pratt', 'Star-Lord in Guardians of the Galaxy.', 8.4),
('Zoe', 'Saldana', 'Played Gamora and Neytiri in Avatar.', 8.7),
('Vin', 'Diesel', 'Voice of Groot and lead in Fast & Furious.', 8.0),
('Bradley', 'Cooper', 'Voices Rocket Raccoon, Oscar-nominated.', 9.0),
('Samuel', 'L. Jackson', 'Nick Fury, long-time Hollywood actor.', 9.4),
('Tom', 'Hanks', 'Known for Forrest Gump and Saving Private Ryan.', 9.5),
('Leonardo', 'DiCaprio', 'Oscar-winning actor known for Titanic.', 9.7),
('Morgan', 'Freeman', 'Known for his deep voice and wise roles.', 9.6),
('Denzel', 'Washington', 'Acclaimed actor in drama and action.', 9.4),
('Natalie', 'Portman', 'Known for Black Swan and Thor.', 8.9),
('Christian', 'Bale', 'Batman in the Dark Knight Trilogy.', 9.2),
('Heath', 'Ledger', 'Oscar for Joker in The Dark Knight.', 9.8),
('Hugh', 'Jackman', 'Known for Wolverine.', 9.0),
('Ryan', 'Reynolds', 'Deadpool and comedic performances.', 8.9),
('Jake', 'Gyllenhaal', 'Donnie Darko, Nightcrawler.', 8.8),
('Anne', 'Hathaway', 'The Devil Wears Prada, Les Misérables.', 8.7),
('Emma', 'Stone', 'Oscar-winning actress.', 8.9),
('Jennifer', 'Lawrence', 'Hunger Games, Silver Linings Playbook.', 9.0),
('Matt', 'Damon', 'Jason Bourne and The Martian.', 8.7),
('Ben', 'Affleck', 'Batman, director and writer.', 8.5),
('Amy', 'Adams', 'Arrival, American Hustle.', 8.8),
('Gal', 'Gadot', 'Wonder Woman.', 8.6),
('Jason', 'Momoa', 'Aquaman and Game of Thrones.', 8.4),
('Henry', 'Cavill', 'Superman and The Witcher.', 8.5),
('Ezra', 'Miller', 'The Flash.', 7.9),
('Meryl', 'Streep', 'Legendary actress with many awards.', 9.8),
('Anthony', 'Hopkins', 'Oscar winner, Hannibal Lecter.', 9.7),
('Joaquin', 'Phoenix', 'Joker, Her, Gladiator.', 9.5),
('Tom', 'Cruise', 'Mission Impossible and Top Gun.', 8.8),
('Keanu', 'Reeves', 'Matrix and John Wick.', 8.9),
('Charlize', 'Theron', 'Monster, Mad Max.', 9.0),
('Michael', 'B. Jordan', 'Creed, Black Panther.', 8.9),
('Brie', 'Larson', 'Captain Marvel, Room.', 8.5),
('Saoirse', 'Ronan', 'Lady Bird, Little Women.', 9.0),
('Florence', 'Pugh', 'Midsommar, Little Women.', 8.8),
('Timothée', 'Chalamet', 'Dune, Call Me by Your Name.', 9.0),
('Zendaya', 'Coleman', 'Euphoria, Spider-Man.', 8.7),
('Andrew', 'Garfield', 'The Social Network, Spider-Man.', 8.9),
('Tobey', 'Maguire', 'First Spider-Man, Seabiscuit.', 8.7),
('Kirsten', 'Dunst', 'Spider-Man, Melancholia.', 8.5),
('Rachel', 'McAdams', 'The Notebook, Doctor Strange.', 8.6),
('Emma', 'Watson', 'Harry Potter, Beauty and the Beast.', 8.9),
('Daniel', 'Radcliffe', 'Harry Potter.', 8.6),
('Rupert', 'Grint', 'Ron Weasley in Harry Potter.', 8.4),
('Michael', 'Fassbender', 'X-Men, Steve Jobs.', 8.7),
('James', 'McAvoy', 'Split, X-Men.', 8.6),
('Ewan', 'McGregor', 'Star Wars, Moulin Rouge.', 8.7),
('Liam', 'Neeson', 'Taken, Schindlers List.', 9.1),
('Harrison', 'Ford', 'Indiana Jones, Star Wars.', 9.0),
('Mark', 'Hamill', 'Luke Skywalker.', 8.5),
('Carrie', 'Fisher', 'Princess Leia.', 8.4),
('Billy', 'Dee Williams', 'Lando Calrissian.', 8.3),
('Donald', 'Glover', 'Solo, Atlanta.', 8.8),
('Woody', 'Harrelson', 'Zombieland, True Detective.', 8.7),
('Matthew', 'McConaughey', 'Dallas Buyers Club, Interstellar.', 9.2),
('Anne', 'Heche', 'Donnie Brasco, Psycho.', 7.8),
('Cillian', 'Murphy', 'Peaky Blinders, Oppenheimer.', 9.1),
('Bryan', 'Cranston', 'Breaking Bad.', 9.5),
('Aaron', 'Paul', 'Breaking Bad.', 8.9),
('Giancarlo', 'Esposito', 'Breaking Bad, The Mandalorian.', 9.0),
('Rosario', 'Dawson', 'The Mandalorian, Daredevil.', 8.6),
('Vincent', 'DOnofrio', 'Kingpin, Law & Order.', 8.7),
('Elizabeth', 'Olsen', 'WandaVision, Marvel films.', 9.0),
('Paul', 'Bettany', 'Vision, WandaVision.', 8.6),
('Tessa', 'Thompson', 'Creed, Thor: Ragnarok.', 8.6),
('Evangeline', 'Lilly', 'Ant-Man, Lost.', 8.5),
('David', 'Harbour', 'Stranger Things, Black Widow.', 8.8),
('Millie', 'Bobby Brown', 'Eleven in Stranger Things.', 8.9),
('Winona', 'Ryder', 'Beetlejuice, Stranger Things.', 8.6),
('Natalia', 'Dyer', 'Stranger Things.', 8.3),
('Finn', 'Wolfhard', 'Stranger Things, Ghostbusters.', 8.4),
('Gaten', 'Matarazzo', 'Stranger Things.', 8.2),
('Caleb', 'McLaughlin', 'Stranger Things.', 8.3),
('Noah', 'Schnapp', 'Stranger Things.', 8.4),
('Sean', 'Astin', 'The Goonies, Lord of the Rings.', 8.9),
('Elijah', 'Wood', 'Frodo in LOTR.', 8.8),
('Ian', 'McKellen', 'Gandalf in LOTR.', 9.5),
('Viggo', 'Mortensen', 'Aragorn in LOTR.', 9.3),
('Orlando', 'Bloom', 'Legolas in LOTR.', 8.5),
('Cate', 'Blanchett', 'Galadriel, Blue Jasmine.', 9.1),
('Hugo', 'Weaving', 'LOTR, The Matrix.', 8.9),
('Liv', 'Tyler', 'LOTR, Armageddon.', 8.4),
('Sean', 'Bean', 'Boromir, Game of Thrones.', 8.8),
('Peter', 'Dinklage', 'Tyrion in Game of Thrones.', 9.3),
('Kit', 'Harington', 'Jon Snow in GoT.', 8.7),
('Emilia', 'Clarke', 'Daenerys Targaryen.', 8.9),
('Sophie', 'Turner', 'Sansa Stark.', 8.5),
('Maisie', 'Williams', 'Arya Stark.', 8.7),
('Nikolaj', 'Coster-Waldau', 'Jaime Lannister.', 8.8);
